image: docker:stable

services:
  - docker:18.09-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:prod || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:prod --tag $CI_REGISTRY_IMAGE:prod --build-arg react_app_api_url=${PROD_API_URL} .
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master

build-staging:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:staging || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:staging --tag $CI_REGISTRY_IMAGE:staging --build-arg react_app_api_url=${STAGING_API_URL} .
    - docker push $CI_REGISTRY_IMAGE:staging
  only:
    - staging
